name: manskelab-py2
channels:
  - conda-forge
  - numerics88
  - defaults
dependencies:
  - aimio=1.0.0
  - boost=1.60.0
  - gdcm=2.8.4
  - n88util=2.0.0
  - pydicom=1.2.2
  - python=2.7
  - vtk=6.3.0
  - vtkbone=1.0.0