name: manskelab-py3
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - python=3.6
  - pydicom=1.2.2
  - gdcm=2.8.4
  - pillow=5.4.1
  - numpy=1.16.2
  - numpy-base=1.16.2
  - numpydoc=0.8.0
  - qt=5.9.7
  - vtk=8.2.0