name: manskelab
channels:
  - anaconda
  - conda-forge
  - numerics88
  - simpleitk
  - defaults
dependencies:
  - aimio=1.0.0
  - boost=1.70.0
  - boost-cpp=1.70.0
  - gdcm=2.8.4
  - matplotlib=3.1.2 
  - n88tools=8.1.0
  - n88util=2.0.0
  - numpy=1.16.2
  - numpy-base=1.16.2
  - numpydoc=0.8.0
  - pillow=5.4.1
  - pip=19.3.1
  - python=3.7.6
  - pydicom=1.2.2
  - qt=5.9.7
  - simpleitk=1.2.4
  - scipy=1.4.1
  - tk=8.6.10
  - vtk=8.2.0
  - vtkbone=1.1.0